mutation CreateItem(
  $name: String!
  $description: String
  $creationTime: Timestamp!
) @auth(level: PUBLIC) {
  item_insert(
    data: {
      name: $name
      description: $description
      creationTime: $creationTime
    }
  )
}
